//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutineCalculation_1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoutineCalculation_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сформировать выборку случайных величин Yi=φ(xi), где Xi – равномерно распределенное число из интервала [a,b], I = 1, …, n.
        ///Величина n задается..
        /// </summary>
        internal static string Task1 {
            get {
                return ResourceManager.GetString("Task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для полученной случайной величины построить вариационный ряд, эмпирическую функцию распределения СВ Y. Результаты представить в виде таблицы и графика..
        /// </summary>
        internal static string Task2 {
            get {
                return ResourceManager.GetString("Task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти теоретически функцию распределения СВ Y.  Результаты представить в аналитическом виде и в виде графика..
        /// </summary>
        internal static string Task3 {
            get {
                return ResourceManager.GetString("Task3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сравнить полученные результаты, представив графики теоретической и эмпирической функций распределения в одном окне..
        /// </summary>
        internal static string Task4 {
            get {
                return ResourceManager.GetString("Task4", resourceCulture);
            }
        }
    }
}
